### PR TITLE
FEATURE:- added welcome message for group

### PR DESCRIPTION
**Pull request by Tomkndn**
- This is fix of #49 

Description: 
- When a user enters a group, for a unknown group first it will suggest to add the group such that the bot can track.
- After adding group, the default welcome message is set.
- Now, a new member enters it will greet with the default welcome message.
- User can also change the welcome message by just writing command !welcome [message].

### CODE REVIEW

**Review by anupammaurya6767 — APPROVED** [review]
@Tomkndn Good work!

**Comment by Tomkndn** [comment]
Thanks, could you please assign and add the required labels under gssoc24.

**Comment by Tomkndn** [comment]
Please add the same label in the issue too.

**Comment by Tomkndn** [comment]
Hey @anupammaurya6767 kindly see the above message please.

**Pull request merged**
